/* EDIT YOUR CATALOG HERE. No build tools needed. See README.md for examples. */
window.STUDIO = {
  // Replace empty strings with real contact details to show the links.
  email: '',
  instagram: '', // Full URL, e.g. https://www.instagram.com/yourname/
  tiktok: '', // Full URL, e.g. https://www.tiktok.com/@yourname
  products: [
    { id: 'bloom', name: 'The Bloom lamp', category: 'Lamps', label: 'A softer kind of glow.', image: 'images/lamp.svg', alt: 'Illustrated sage green mushroom lamp with a pleated shade', badge: 'STUDIO FAVORITE', description: 'A sculptural little companion for your bedside or favorite reading corner. A pleated shade and a simple silhouette bring a soft, playful touch to your space.', details: ['Concept shown: sage green', 'Ask about available colors', 'Lighting specifications confirmed on enquiry'] },
    { id: 'garden', name: 'Garden party cutters', category: 'Cookie cutters', label: 'A little joy in every batch.', image: 'images/cutters.svg', alt: 'Illustrated flower, heart, and arch cookie cutter shapes in pastel colors', badge: '', description: 'Flower shapes, soft arches, and sweet little hearts for your next baking idea. This playful set is a starting point for a celebration with personality.', details: ['Example collection: three playful shapes', 'Custom shapes and sizes can be discussed', 'Ask about material suitability and care before food use'] },
    { id: 'finish-line', name: 'The finish line', category: 'Medal hangers', label: 'Your effort deserves a place.', image: 'images/medals.svg', alt: 'Illustrated dark medal hanger with mountain detail and three hanging medals', badge: 'MAKE IT PERSONAL', description: 'A dedicated spot for the moments you worked for. A mountain-inspired display turns your collection of medals into an everyday reminder of how far you’ve come.', details: ['Concept shown: charcoal with mountain detail', 'Personalize a name or short phrase', 'Mounting details and capacity confirmed on enquiry'] },
    { id: 'ripple', name: 'The Ripple lamp', category: 'Lamps', label: 'Warm light. Quiet character.', image: 'images/ripple.svg', alt: 'Illustrated ivory sculptural lamp with a wavy silhouette', badge: '', description: 'Soft curves and a rippled surface give this lamp its quiet character. An understated accent for a desk, sideboard, or cozy nook.', details: ['Concept shown: warm ivory', 'Ask about dimensions and finish options', 'Lighting specifications confirmed on enquiry'] },
    { id: 'little-celebrations', name: 'Little celebrations', category: 'Cookie cutters', label: 'Made for your special moments.', image: 'images/custom-cutter.svg', alt: 'Illustrated terracotta star and personalized arch cutter', badge: 'MAKE IT PERSONAL', description: 'A birthday, a little milestone, or just a reason to bake. Explore personalized lettering and shapes designed around your celebration.', details: ['Personalized lettering concept', 'Share your occasion and preferred size', 'Ask about material suitability and care before food use'] },
    { id: 'your-pace', name: 'At your own pace', category: 'Medal hangers', label: 'Every little victory belongs.', image: 'images/runner.svg', alt: 'Illustrated sage medal display with a running track motif and two medals', badge: '', description: 'Big milestones and first finishes alike deserve to be remembered. A simple, graphic medal display with room for a personal touch.', details: ['Concept shown: muted sage', 'Discuss your own wording or motif', 'Mounting details and capacity confirmed on enquiry'] }
  ]
};
